<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Product>AnotherFSM</Product>
    <Company />
    <Authors>Naoki</Authors>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageReleaseNotes></PackageReleaseNotes>
    <RepositoryUrl>https://github.com/Naoki326/AnotherFSM</RepositoryUrl>
    <Copyright></Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.EN.md</PackageReadmeFile>
    <Description>A tool library for quickly constructing processes based on finite state machines.</Description>
    <PackageId>Naoki.AnotherFSM</PackageId>
    <Version>1.1.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.EN.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="System.Reactive" Version="6.0.0" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>

</Project>
