//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/zhiyuan/source/repos/AnotherFSM/StateMachine/Engine/StateMachineScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class StateMachineScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, NONE=19, NEXT=20, SUCCESS=21, FAILED=22, ERROR=23, BREAK=24, 
		CANCEL=25, TRIGGER=26, COLON=27, SEMICOLON=28, CODESTRING=29, GUID=30, 
		STRING=31, INT=32, DOUBLE=33, WS=34, COMMENT=35, LINE_COMMENT=36;
	public const int
		RULE_machine = 0, RULE_namespace = 1, RULE_expression = 2, RULE_state_statement = 3, 
		RULE_state_branch = 4, RULE_position = 5, RULE_posx = 6, RULE_posy = 7, 
		RULE_event_statement = 8, RULE_transition = 9;
	public static readonly string[] ruleNames = {
		"machine", "namespace", "expression", "state_statement", "state_branch", 
		"position", "posx", "posy", "event_statement", "transition"
	};

	private static readonly string[] _LiteralNames = {
		null, "'namespace'", "'{'", "'}'", "'def'", "'as'", "'state'", "'('", 
		"')'", "'branch'", "'Pos'", "'Color'", "'Type'", "'FlowID'", "'['", "']'", 
		"','", "'event'", "'to'", "'none'", "'next'", "'success'", "'failed'", 
		"'error'", "'break'", "'cancel'", null, "':'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "NONE", "NEXT", "SUCCESS", "FAILED", 
		"ERROR", "BREAK", "CANCEL", "TRIGGER", "COLON", "SEMICOLON", "CODESTRING", 
		"GUID", "STRING", "INT", "DOUBLE", "WS", "COMMENT", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "StateMachineScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static StateMachineScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public StateMachineScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public StateMachineScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class MachineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NamespaceContext[] @namespace() {
			return GetRuleContexts<NamespaceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NamespaceContext @namespace(int i) {
			return GetRuleContext<NamespaceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(StateMachineScriptParser.Eof, 0); }
		public MachineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_machine; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterMachine(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitMachine(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMachine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MachineContext machine() {
		MachineContext _localctx = new MachineContext(Context, State);
		EnterRule(_localctx, 0, RULE_machine);
		int _la;
		try {
			State = 33;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 23;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 6508019216L) != 0)) {
					{
					{
					State = 20;
					expression();
					}
					}
					State = 25;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 29;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__0) {
					{
					{
					State = 26;
					@namespace();
					}
					}
					State = 31;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 32;
				Match(Eof);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(StateMachineScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public NamespaceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterNamespace(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitNamespace(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespace(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceContext @namespace() {
		NamespaceContext _localctx = new NamespaceContext(Context, State);
		EnterRule(_localctx, 2, RULE_namespace);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			Match(T__0);
			State = 36;
			Match(STRING);
			State = 37;
			Match(T__1);
			State = 41;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 6508019216L) != 0)) {
				{
				{
				State = 38;
				expression();
				}
				}
				State = 43;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 44;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public State_statementContext state_statement() {
			return GetRuleContext<State_statementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Event_statementContext event_statement() {
			return GetRuleContext<Event_statementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TransitionContext transition() {
			return GetRuleContext<TransitionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public State_branchContext state_branch() {
			return GetRuleContext<State_branchContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 4, RULE_expression);
		try {
			State = 50;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 46;
				state_statement();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 47;
				event_statement();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 48;
				transition();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 49;
				state_branch();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class State_statementContext : ParserRuleContext {
		public State_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_state_statement; } }
	 
		public State_statementContext() { }
		public virtual void CopyFrom(State_statementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DefState2Context : State_statementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(StateMachineScriptParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(StateMachineScriptParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public State_branchContext[] state_branch() {
			return GetRuleContexts<State_branchContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public State_branchContext state_branch(int i) {
			return GetRuleContext<State_branchContext>(i);
		}
		public DefState2Context(State_statementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterDefState2(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitDefState2(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefState2(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DefStateContext : State_statementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(StateMachineScriptParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(StateMachineScriptParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public State_branchContext[] state_branch() {
			return GetRuleContexts<State_branchContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public State_branchContext state_branch(int i) {
			return GetRuleContext<State_branchContext>(i);
		}
		public DefStateContext(State_statementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterDefState(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitDefState(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefState(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public State_statementContext state_statement() {
		State_statementContext _localctx = new State_statementContext(Context, State);
		EnterRule(_localctx, 6, RULE_state_statement);
		int _la;
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				_localctx = new DefStateContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 52;
				Match(T__3);
				State = 53;
				Match(STRING);
				State = 54;
				Match(T__4);
				State = 56;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==STRING) {
					{
					State = 55;
					Match(STRING);
					}
				}

				State = 58;
				Match(T__5);
				State = 59;
				Match(T__1);
				State = 63;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 4360535552L) != 0)) {
					{
					{
					State = 60;
					state_branch();
					}
					}
					State = 65;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 66;
				Match(T__2);
				}
				break;
			case 2:
				_localctx = new DefState2Context(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 67;
				Match(T__3);
				State = 68;
				Match(STRING);
				State = 69;
				Match(T__6);
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==STRING) {
					{
					State = 70;
					Match(STRING);
					}
				}

				State = 73;
				Match(T__7);
				State = 74;
				Match(T__1);
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 4360535552L) != 0)) {
					{
					{
					State = 75;
					state_branch();
					}
					}
					State = 80;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 81;
				Match(T__2);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class State_branchContext : ParserRuleContext {
		public State_branchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_state_branch; } }
	 
		public State_branchContext() { }
		public virtual void CopyFrom(State_branchContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FlowIDDefContext : State_branchContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(StateMachineScriptParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GUID() { return GetToken(StateMachineScriptParser.GUID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(StateMachineScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(StateMachineScriptParser.INT, 0); }
		public FlowIDDefContext(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterFlowIDDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitFlowIDDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFlowIDDef(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DefBranchContext : State_branchContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(StateMachineScriptParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRIGGER() { return GetToken(StateMachineScriptParser.TRIGGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(StateMachineScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public DefBranchContext(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterDefBranch(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitDefBranch(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefBranch(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PosDefContext : State_branchContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(StateMachineScriptParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PositionContext position() {
			return GetRuleContext<PositionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public PosDefContext(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterPosDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitPosDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPosDef(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TypeDefContext : State_branchContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(StateMachineScriptParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(StateMachineScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public TypeDefContext(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterTypeDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitTypeDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDef(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GroudFSMDefContext : State_branchContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(StateMachineScriptParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(StateMachineScriptParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRIGGER() { return GetToken(StateMachineScriptParser.TRIGGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public GroudFSMDefContext(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterGroudFSMDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitGroudFSMDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGroudFSMDef(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DefBranch2Context : State_branchContext {
		public IToken branch_type;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRIGGER() { return GetToken(StateMachineScriptParser.TRIGGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(StateMachineScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(StateMachineScriptParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NONE() { return GetToken(StateMachineScriptParser.NONE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SUCCESS() { return GetToken(StateMachineScriptParser.SUCCESS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FAILED() { return GetToken(StateMachineScriptParser.FAILED, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ERROR() { return GetToken(StateMachineScriptParser.ERROR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BREAK() { return GetToken(StateMachineScriptParser.BREAK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CANCEL() { return GetToken(StateMachineScriptParser.CANCEL, 0); }
		public DefBranch2Context(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterDefBranch2(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitDefBranch2(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefBranch2(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ColorDefContext : State_branchContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(StateMachineScriptParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CODESTRING() { return GetToken(StateMachineScriptParser.CODESTRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public ColorDefContext(State_branchContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterColorDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitColorDef(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColorDef(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public State_branchContext state_branch() {
		State_branchContext _localctx = new State_branchContext(Context, State);
		EnterRule(_localctx, 8, RULE_state_branch);
		int _la;
		try {
			State = 116;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__8:
				_localctx = new DefBranchContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 84;
				Match(T__8);
				State = 85;
				Match(INT);
				State = 86;
				Match(TRIGGER);
				State = 87;
				Match(STRING);
				State = 88;
				Match(SEMICOLON);
				}
				break;
			case NONE:
			case SUCCESS:
			case FAILED:
			case ERROR:
			case BREAK:
			case CANCEL:
			case INT:
				_localctx = new DefBranch2Context(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 89;
				((DefBranch2Context)_localctx).branch_type = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 4360503296L) != 0)) ) {
					((DefBranch2Context)_localctx).branch_type = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 90;
				Match(TRIGGER);
				State = 91;
				Match(STRING);
				State = 92;
				Match(SEMICOLON);
				}
				break;
			case T__9:
				_localctx = new PosDefContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 93;
				Match(T__9);
				State = 94;
				Match(COLON);
				State = 95;
				position();
				State = 96;
				Match(SEMICOLON);
				}
				break;
			case T__10:
				_localctx = new ColorDefContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 98;
				Match(T__10);
				State = 99;
				Match(COLON);
				State = 100;
				Match(CODESTRING);
				State = 101;
				Match(SEMICOLON);
				}
				break;
			case T__11:
				_localctx = new TypeDefContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 102;
				Match(T__11);
				State = 103;
				Match(COLON);
				State = 104;
				Match(STRING);
				State = 105;
				Match(SEMICOLON);
				}
				break;
			case T__12:
				_localctx = new FlowIDDefContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 106;
				Match(T__12);
				State = 107;
				Match(COLON);
				State = 108;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7516192768L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 109;
				Match(SEMICOLON);
				}
				break;
			case T__13:
				_localctx = new GroudFSMDefContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 110;
				Match(T__13);
				State = 111;
				Match(STRING);
				State = 112;
				Match(TRIGGER);
				State = 113;
				Match(STRING);
				State = 114;
				Match(T__14);
				State = 115;
				Match(SEMICOLON);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PositionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PosxContext posx() {
			return GetRuleContext<PosxContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PosyContext posy() {
			return GetRuleContext<PosyContext>(0);
		}
		public PositionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_position; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterPosition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitPosition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPosition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PositionContext position() {
		PositionContext _localctx = new PositionContext(Context, State);
		EnterRule(_localctx, 10, RULE_position);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			Match(T__6);
			State = 119;
			posx();
			State = 120;
			Match(T__15);
			State = 121;
			posy();
			State = 122;
			Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PosxContext : ParserRuleContext {
		public PosxContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_posx; } }
	 
		public PosxContext() { }
		public virtual void CopyFrom(PosxContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class POSXContext : PosxContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(StateMachineScriptParser.DOUBLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(StateMachineScriptParser.INT, 0); }
		public POSXContext(PosxContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterPOSX(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitPOSX(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPOSX(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PosxContext posx() {
		PosxContext _localctx = new PosxContext(Context, State);
		EnterRule(_localctx, 12, RULE_posx);
		int _la;
		try {
			_localctx = new POSXContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			_la = TokenStream.LA(1);
			if ( !(_la==INT || _la==DOUBLE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PosyContext : ParserRuleContext {
		public PosyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_posy; } }
	 
		public PosyContext() { }
		public virtual void CopyFrom(PosyContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class POSYContext : PosyContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(StateMachineScriptParser.DOUBLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(StateMachineScriptParser.INT, 0); }
		public POSYContext(PosyContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterPOSY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitPOSY(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPOSY(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PosyContext posy() {
		PosyContext _localctx = new PosyContext(Context, State);
		EnterRule(_localctx, 14, RULE_posy);
		int _la;
		try {
			_localctx = new POSYContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			_la = TokenStream.LA(1);
			if ( !(_la==INT || _la==DOUBLE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Event_statementContext : ParserRuleContext {
		public Event_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_event_statement; } }
	 
		public Event_statementContext() { }
		public virtual void CopyFrom(Event_statementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DefEventContext : Event_statementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(StateMachineScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public DefEventContext(Event_statementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterDefEvent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitDefEvent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefEvent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Event_statementContext event_statement() {
		Event_statementContext _localctx = new Event_statementContext(Context, State);
		EnterRule(_localctx, 16, RULE_event_statement);
		int _la;
		try {
			_localctx = new DefEventContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			Match(T__3);
			State = 129;
			Match(STRING);
			State = 131;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__4) {
				{
				State = 130;
				Match(T__4);
				}
			}

			State = 133;
			Match(T__16);
			State = 134;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TransitionContext : ParserRuleContext {
		public TransitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_transition; } }
	 
		public TransitionContext() { }
		public virtual void CopyFrom(TransitionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DefTransitionContext : TransitionContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(StateMachineScriptParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(StateMachineScriptParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRIGGER() { return GetToken(StateMachineScriptParser.TRIGGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(StateMachineScriptParser.SEMICOLON, 0); }
		public DefTransitionContext(TransitionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.EnterDefTransition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IStateMachineScriptListener typedListener = listener as IStateMachineScriptListener;
			if (typedListener != null) typedListener.ExitDefTransition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStateMachineScriptVisitor<TResult> typedVisitor = visitor as IStateMachineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefTransition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TransitionContext transition() {
		TransitionContext _localctx = new TransitionContext(Context, State);
		EnterRule(_localctx, 18, RULE_transition);
		try {
			_localctx = new DefTransitionContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 136;
			Match(STRING);
			State = 137;
			Match(TRIGGER);
			State = 138;
			Match(STRING);
			State = 139;
			Match(T__17);
			State = 140;
			Match(STRING);
			State = 141;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,36,144,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,1,0,5,0,22,8,0,10,0,12,0,25,9,0,1,0,5,0,28,8,0,10,
		0,12,0,31,9,0,1,0,3,0,34,8,0,1,1,1,1,1,1,1,1,5,1,40,8,1,10,1,12,1,43,9,
		1,1,1,1,1,1,2,1,2,1,2,1,2,3,2,51,8,2,1,3,1,3,1,3,1,3,3,3,57,8,3,1,3,1,
		3,1,3,5,3,62,8,3,10,3,12,3,65,9,3,1,3,1,3,1,3,1,3,1,3,3,3,72,8,3,1,3,1,
		3,1,3,5,3,77,8,3,10,3,12,3,80,9,3,1,3,3,3,83,8,3,1,4,1,4,1,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,
		1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,117,8,4,1,5,1,5,1,5,1,5,1,5,1,
		5,1,6,1,6,1,7,1,7,1,8,1,8,1,8,3,8,132,8,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,
		1,9,1,9,1,9,1,9,0,0,10,0,2,4,6,8,10,12,14,16,18,0,3,3,0,19,19,21,25,32,
		32,1,0,30,32,1,0,32,33,153,0,33,1,0,0,0,2,35,1,0,0,0,4,50,1,0,0,0,6,82,
		1,0,0,0,8,116,1,0,0,0,10,118,1,0,0,0,12,124,1,0,0,0,14,126,1,0,0,0,16,
		128,1,0,0,0,18,136,1,0,0,0,20,22,3,4,2,0,21,20,1,0,0,0,22,25,1,0,0,0,23,
		21,1,0,0,0,23,24,1,0,0,0,24,34,1,0,0,0,25,23,1,0,0,0,26,28,3,2,1,0,27,
		26,1,0,0,0,28,31,1,0,0,0,29,27,1,0,0,0,29,30,1,0,0,0,30,34,1,0,0,0,31,
		29,1,0,0,0,32,34,5,0,0,1,33,23,1,0,0,0,33,29,1,0,0,0,33,32,1,0,0,0,34,
		1,1,0,0,0,35,36,5,1,0,0,36,37,5,31,0,0,37,41,5,2,0,0,38,40,3,4,2,0,39,
		38,1,0,0,0,40,43,1,0,0,0,41,39,1,0,0,0,41,42,1,0,0,0,42,44,1,0,0,0,43,
		41,1,0,0,0,44,45,5,3,0,0,45,3,1,0,0,0,46,51,3,6,3,0,47,51,3,16,8,0,48,
		51,3,18,9,0,49,51,3,8,4,0,50,46,1,0,0,0,50,47,1,0,0,0,50,48,1,0,0,0,50,
		49,1,0,0,0,51,5,1,0,0,0,52,53,5,4,0,0,53,54,5,31,0,0,54,56,5,5,0,0,55,
		57,5,31,0,0,56,55,1,0,0,0,56,57,1,0,0,0,57,58,1,0,0,0,58,59,5,6,0,0,59,
		63,5,2,0,0,60,62,3,8,4,0,61,60,1,0,0,0,62,65,1,0,0,0,63,61,1,0,0,0,63,
		64,1,0,0,0,64,66,1,0,0,0,65,63,1,0,0,0,66,83,5,3,0,0,67,68,5,4,0,0,68,
		69,5,31,0,0,69,71,5,7,0,0,70,72,5,31,0,0,71,70,1,0,0,0,71,72,1,0,0,0,72,
		73,1,0,0,0,73,74,5,8,0,0,74,78,5,2,0,0,75,77,3,8,4,0,76,75,1,0,0,0,77,
		80,1,0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,79,81,1,0,0,0,80,78,1,0,0,0,81,
		83,5,3,0,0,82,52,1,0,0,0,82,67,1,0,0,0,83,7,1,0,0,0,84,85,5,9,0,0,85,86,
		5,32,0,0,86,87,5,26,0,0,87,88,5,31,0,0,88,117,5,28,0,0,89,90,7,0,0,0,90,
		91,5,26,0,0,91,92,5,31,0,0,92,117,5,28,0,0,93,94,5,10,0,0,94,95,5,27,0,
		0,95,96,3,10,5,0,96,97,5,28,0,0,97,117,1,0,0,0,98,99,5,11,0,0,99,100,5,
		27,0,0,100,101,5,29,0,0,101,117,5,28,0,0,102,103,5,12,0,0,103,104,5,27,
		0,0,104,105,5,31,0,0,105,117,5,28,0,0,106,107,5,13,0,0,107,108,5,27,0,
		0,108,109,7,1,0,0,109,117,5,28,0,0,110,111,5,14,0,0,111,112,5,31,0,0,112,
		113,5,26,0,0,113,114,5,31,0,0,114,115,5,15,0,0,115,117,5,28,0,0,116,84,
		1,0,0,0,116,89,1,0,0,0,116,93,1,0,0,0,116,98,1,0,0,0,116,102,1,0,0,0,116,
		106,1,0,0,0,116,110,1,0,0,0,117,9,1,0,0,0,118,119,5,7,0,0,119,120,3,12,
		6,0,120,121,5,16,0,0,121,122,3,14,7,0,122,123,5,8,0,0,123,11,1,0,0,0,124,
		125,7,2,0,0,125,13,1,0,0,0,126,127,7,2,0,0,127,15,1,0,0,0,128,129,5,4,
		0,0,129,131,5,31,0,0,130,132,5,5,0,0,131,130,1,0,0,0,131,132,1,0,0,0,132,
		133,1,0,0,0,133,134,5,17,0,0,134,135,5,28,0,0,135,17,1,0,0,0,136,137,5,
		31,0,0,137,138,5,26,0,0,138,139,5,31,0,0,139,140,5,18,0,0,140,141,5,31,
		0,0,141,142,5,28,0,0,142,19,1,0,0,0,12,23,29,33,41,50,56,63,71,78,82,116,
		131
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
