using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
// no runtime dependency on StateMachine here; we only emit code that references it in generated sources

namespace FSMScriptAnalyzer
{
    [Generator]
    public class FSMScriptAnalyzerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var scripts = context.AdditionalTextsProvider
                .Where(at => at.Path.EndsWith(".FSMScript", StringComparison.OrdinalIgnoreCase))
                .Select((text, ct) => new ScriptInfo(
                    Path.GetFileNameWithoutExtension(text.Path),
                    text.Path,
                    text.GetText(ct)?.ToString() ?? string.Empty));

            var filtered = scripts.Where(s => !string.IsNullOrWhiteSpace(s.Content));

            var fsmModuleIndex = context.AdditionalTextsProvider
                .Where(at => at.Path.EndsWith(".fsm", StringComparison.OrdinalIgnoreCase))
                .Select((text, ct) => new KeyValuePair<string, string>(
                    Path.GetFileNameWithoutExtension(text.Path),
                    text.GetText(ct)?.ToString() ?? string.Empty))
                .Collect()
                .Select((pairs, _) => pairs.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value,
                    StringComparer.OrdinalIgnoreCase));

            var compilation = context.CompilationProvider;
            var rootNamespace = context.AnalyzerConfigOptionsProvider
                .Select((opts, _) =>
                {
                    return opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) ? ns : null;
                });

            var combined = filtered.Combine(compilation).Combine(rootNamespace).Combine(fsmModuleIndex);

            context.RegisterSourceOutput(combined, (spc, triple) =>
            {
                var s = triple.Left.Left.Left;
                var comp = triple.Left.Left.Right;
                var ns = triple.Left.Right;
                var moduleIndex = triple.Right;
                var typeMap = BuildNodeTypeMap(comp);
                var nodes = ParseNodes(s.Content);
                var events = ParseEvents(s.Content);
                var moduleNames = new HashSet<string>(moduleIndex.Keys, StringComparer.OrdinalIgnoreCase);
                var targetNs = string.IsNullOrWhiteSpace(ns) ? comp.AssemblyName ?? "FSM" : ns!;
                var source = GenerateScriptClassSource(s, nodes, events, typeMap, targetNs, moduleIndex, moduleNames);
                var hintName = $"{targetNs}.{s.FileName}.g.cs";
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            });
        }

        private static string GenerateScriptClassSource(ScriptInfo s, List<NodeDef> nodes, List<string> events, Dictionary<string, string> typeMap, string targetNamespace, Dictionary<string, string> moduleIndex, HashSet<string> moduleNames)
        {
            var moduleScripts = CollectModuleScripts(s.Content, moduleIndex);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
            var className = MakeIdentifier(s.FileName);
            sb.AppendLine($"    public class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static string ScriptText => @\"{EscapeForVerbatimString(s.Content)}\";");
            sb.AppendLine();

            if (moduleScripts.Length > 0)
            {
                sb.AppendLine("        public static string[] ModuleScripts => new[] {");
                for (int i = 0; i < moduleScripts.Length; i++)
                {
                    var comma = i < moduleScripts.Length - 1 ? "," : "";
                    sb.AppendLine($"            @\"{EscapeForVerbatimString(moduleScripts[i])}\"{comma}");
                }
                sb.AppendLine("        };");
            }
            else
            {
                sb.AppendLine("        public static string[] ModuleScripts => new string[] { };");
            }
            sb.AppendLine();

            sb.AppendLine($"        public static {className} Create(StateMachine.IFSMNodeFactory factory)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {className}(factory);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private {className}() {{ }}");
            sb.AppendLine();
            sb.AppendLine("        public StateMachine.FSMEngine Engine { get; }");
            sb.AppendLine();
            sb.AppendLine($"        public {className}(StateMachine.IFSMNodeFactory factory)");
            sb.AppendLine("        {");
            sb.AppendLine("            Engine = new StateMachine.FSMEngine(factory);");
            if (moduleScripts.Length > 0)
            {
                sb.AppendLine("            foreach (var ms in ModuleScripts)");
                sb.AppendLine("            {");
                sb.AppendLine("                var moduleName = ParseModuleName(ms);");
                sb.AppendLine("                if (!string.IsNullOrEmpty(moduleName))");
                sb.AppendLine("                {");
                sb.AppendLine("                    Engine.RegisterModule(moduleName, ms);");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
            }
            sb.AppendLine("            Engine.CreateStateMachine(ScriptText);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string ParseModuleName(string script)");
            sb.AppendLine("        {");
            sb.AppendLine("            var match = System.Text.RegularExpressions.Regex.Match(script, @\"module\\s+([_\\w][_\\w.]*)\\s*(?:as\\s+[_\\w][_\\w.]*\\s*)?\\{\");");
            sb.AppendLine("            return match.Success ? match.Groups[1].Value : string.Empty;");
            sb.AppendLine("        }");
            foreach (var n in nodes)
            {
                var propName = MakeIdentifier(n.NodeName);
                sb.AppendLine();
                if (moduleNames.Contains(n.NodeTypeKey))
                {
                    sb.AppendLine($"        public global::StateMachine.IFSMNode {propName} => Engine.GetNode<global::StateMachine.IFSMNode>(\"{n.NodeName}\");");
                }
                else
                {
                    typeMap.TryGetValue(n.NodeTypeKey, out var typeFullName);
                    typeFullName ??= "global::StateMachine.IFSMNode";
                    sb.AppendLine($"        public {typeFullName} {propName} => Engine.GetNode<{typeFullName}>(\"{n.NodeName}\");");
                }
            }
            foreach (var ev in events.Distinct(StringComparer.Ordinal))
            {
                var propName = MakeIdentifier(ev);
                sb.AppendLine();
                sb.AppendLine($"        public global::StateMachine.FSMEvent {propName} => Engine.GetEvent(\"{ev}\");");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string[] CollectModuleScripts(string script, Dictionary<string, string> moduleIndex)
        {
            var result = new List<string>();
            var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            CollectRecursive(script, moduleIndex, visited, result);
            return result.ToArray();
        }

        private static void CollectRecursive(string script, Dictionary<string, string> moduleIndex, HashSet<string> visited, List<string> result)
        {
            var imports = ParseImportStatements(script);
            foreach (var import in imports)
            {
                if (!visited.Add(import)) continue;
                if (moduleIndex.TryGetValue(import, out var moduleContent))
                {
                    result.Add(moduleContent);
                    CollectRecursive(moduleContent, moduleIndex, visited, result);
                }
            }
        }

        private static List<string> ParseImportStatements(string script)
        {
            // 移除块注释 /* ... */
            var cleaned = Regex.Replace(script, @"/\*.*?\*/", " ", RegexOptions.Singleline);
            // 移除行注释 // ...
            cleaned = Regex.Replace(cleaned, @"//[^\r\n]*", " ");
            // 移除字符串字面量 " ... "
            cleaned = Regex.Replace(cleaned, @"""[^""]*""", "\"\"");

            var result = new List<string>();
            var matches = Regex.Matches(cleaned, @"import\s+([_\w][_\w.]*)");
            foreach (Match match in matches)
                result.Add(match.Groups[1].Value);
            return result;
        }

        private static string EscapeForVerbatimString(string input)
        {
            return input.Replace("\"", "\"\"");
        }

        private static string MakeIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw)) return "FSM_Script";
            var s = new string(raw.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray());
            if (!Microsoft.CodeAnalysis.CSharp.SyntaxFacts.IsValidIdentifier(s)) s = "FSM_Script";
            return s;
        }

        private sealed class NodeDef
        {
            public string NodeName { get; set; } = string.Empty;
            public string NodeTypeKey { get; set; } = string.Empty;
        }

        private readonly struct ScriptInfo : IEquatable<ScriptInfo>
        {
            public string FileName { get; }
            public string Path { get; }
            public string Content { get; }

            public ScriptInfo(string fileName, string path, string content)
            {
                FileName = fileName ?? string.Empty;
                Path = path ?? string.Empty;
                Content = content ?? string.Empty;
            }

            public bool Equals(ScriptInfo other)
            {
                return string.Equals(Path, other.Path, StringComparison.OrdinalIgnoreCase)
                    && string.Equals(Content, other.Content, StringComparison.Ordinal);
            }

            public override bool Equals(object? obj)
            {
                return obj is ScriptInfo other && Equals(other);
            }

            public override int GetHashCode()
            {
                unchecked
                {
                    var h1 = StringComparer.OrdinalIgnoreCase.GetHashCode(Path);
                    var h2 = StringComparer.Ordinal.GetHashCode(Content);
                    return (h1 * 397) ^ h2;
                }
            }
        }

        private static Dictionary<string, string> BuildNodeTypeMap(Compilation compilation)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var attr = compilation.GetTypeByMetadataName("StateMachine.FSMNodeAttribute");
            if (attr == null) return result;

            void Traverse(INamespaceSymbol ns)
            {
                foreach (var m in ns.GetMembers())
                {
                    if (m is INamespaceSymbol childNs)
                    {
                        Traverse(childNs);
                    }
                    else if (m is INamedTypeSymbol type)
                    {
                        foreach (var a in type.GetAttributes())
                        {
                            if (!SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr)) continue;
                            string? key = null;
                            if (a.ConstructorArguments.Length > 0)
                            {
                                var arg = a.ConstructorArguments[0];
                                if (arg.Kind == TypedConstantKind.Primitive && arg.Value is string s) key = s;
                            }
                            if (key is null)
                            {
                                foreach (var na in a.NamedArguments)
                                {
                                    if (na.Key == "Key" && na.Value.Kind == TypedConstantKind.Primitive && na.Value.Value is string ks)
                                    {
                                        key = ks;
                                        break;
                                    }
                                }
                            }
                            if (!string.IsNullOrWhiteSpace(key))
                            {
                                var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                                if (!result.ContainsKey(key)) result[key] = fullName;
                            }
                        }
                    }
                }
            }
            Traverse(compilation.GlobalNamespace);
            return result;
        }

        private static List<NodeDef> ParseNodes(string script)
        {
            var list = new List<NodeDef>();
            var reader = new StringReader(script);
            string? line;
            while ((line = reader.ReadLine()) != null)
            {
                line = line.Trim();
                if (!line.StartsWith("def ", StringComparison.OrdinalIgnoreCase)) continue;
                var idxDef = line.IndexOf(' ');
                if (idxDef < 0) continue;
                var afterDef = line.Substring(idxDef + 1);
                var idxParenOpen = afterDef.IndexOf('(');
                var idxParenClose = afterDef.IndexOf(')');
                if (idxParenOpen < 0 || idxParenClose < 0 || idxParenClose <= idxParenOpen) continue;
                var name = afterDef.Substring(0, idxParenOpen).Trim();
                var typeKey = afterDef.Substring(idxParenOpen + 1, idxParenClose - idxParenOpen - 1).Trim();
                if (name.Length == 0 || typeKey.Length == 0) continue;
                list.Add(new NodeDef { NodeName = name, NodeTypeKey = typeKey });
            }
            return list;
        }

        private static List<string> ParseEvents(string script)
        {
            var set = new HashSet<string>(StringComparer.Ordinal);
            var reader = new StringReader(script);
            string? line;
            while ((line = reader.ReadLine()) != null)
            {
                var t = line.Trim();
                if (t.Length == 0) continue;
                if (t.Contains("->"))
                {
                    var parts = t.Split(new[] { "->" }, StringSplitOptions.None);
                    if (parts.Length >= 2)
                    {
                        var left = parts[0].Trim();
                        var right = parts[1].Trim();
                        var semiIdx = right.IndexOf(';');
                        if (semiIdx >= 0) right = right.Substring(0, semiIdx).Trim();
                        if (!string.IsNullOrEmpty(left) && !char.IsDigit(left[0]))
                        {
                            set.Add(left);
                        }
                        else
                        {
                            var idxNameEnd = right.IndexOfAny(new[] { ' ', '\t' });
                            var evName = idxNameEnd > 0 ? right.Substring(0, idxNameEnd).Trim() : right.Trim();
                            if (!string.IsNullOrEmpty(evName) && evName.IndexOf(':') < 0)
                            {
                                set.Add(evName);
                            }
                        }
                    }
                }
            }
            return set.ToList();
        }
    }
}
