using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
// no runtime dependency on StateMachine here; we only emit code that references it in generated sources

namespace FSMScriptAnalyzer
{
    [Generator]
    public class FSMScriptAnalyzerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var scripts = context.AdditionalTextsProvider
                .Where(at => at.Path.EndsWith(".FSMScript", StringComparison.OrdinalIgnoreCase))
                .Select((text, ct) => new ScriptInfo(
                    Path.GetFileNameWithoutExtension(text.Path),
                    text.Path,
                    text.GetText(ct)?.ToString() ?? string.Empty));

            var filtered = scripts.Where(s => !string.IsNullOrWhiteSpace(s.Content));
            var compilation = context.CompilationProvider;
            var rootNamespace = context.AnalyzerConfigOptionsProvider
                .Select((opts, _) =>
                {
                    return opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) ? ns : null;
                });

            var combined = filtered.Combine(compilation).Combine(rootNamespace);

            context.RegisterSourceOutput(combined, (spc, triple) =>
            {
                var s = triple.Left.Left;
                var comp = triple.Left.Right;
                var ns = triple.Right;
                var typeMap = BuildNodeTypeMap(comp);
                var nodes = ParseNodes(s.Content);
                var targetNs = string.IsNullOrWhiteSpace(ns) ? comp.AssemblyName ?? "FSM" : ns!;
                var source = GenerateScriptClassSource(s, nodes, typeMap, targetNs);
                var hintName = $"{targetNs}.{s.FileName}.g.cs";
                spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            });
        }

        private static string GenerateScriptClassSource(ScriptInfo s, List<NodeDef> nodes, Dictionary<string, string> typeMap, string targetNamespace)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
            var className = MakeIdentifier(s.FileName);
            sb.AppendLine($"    public class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static string ScriptText => @\"{EscapeForVerbatimString(s.Content)}\";");
            sb.AppendLine();
            sb.AppendLine($"        public static {className} Create(StateMachine.IFSMNodeFactory factory)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {className}(factory);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private {className}() {{ }}");
            sb.AppendLine();
            sb.AppendLine("        public StateMachine.FSMEngine Engine { get; }");
            sb.AppendLine();
            sb.AppendLine($"        public {className}(StateMachine.IFSMNodeFactory factory)");
            sb.AppendLine("        {");
            sb.AppendLine("            Engine = new StateMachine.FSMEngine(factory);");
            sb.AppendLine("            Engine.CreateStateMachine(ScriptText);");
            sb.AppendLine("        }");
            foreach (var n in nodes)
            {
                var propName = MakeIdentifier(n.NodeName);
                typeMap.TryGetValue(n.NodeTypeKey, out var typeFullName);
                typeFullName ??= "global::StateMachine.IFSMNode";
                sb.AppendLine();
                sb.AppendLine($"        public {typeFullName} {propName} => Engine.GetNode<{typeFullName}>(\"{n.NodeName}\");");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string EscapeForVerbatimString(string input)
        {
            return input.Replace("\"", "\"\"");
        }

        private static string MakeIdentifier(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw)) return "FSM_Script";
            var s = new string(raw.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray());
            if (!Microsoft.CodeAnalysis.CSharp.SyntaxFacts.IsValidIdentifier(s)) s = "FSM_Script";
            return s;
        }

        private sealed class NodeDef
        {
            public string NodeName { get; set; } = string.Empty;
            public string NodeTypeKey { get; set; } = string.Empty;
        }

        private readonly struct ScriptInfo : IEquatable<ScriptInfo>
        {
            public string FileName { get; }
            public string Path { get; }
            public string Content { get; }

            public ScriptInfo(string fileName, string path, string content)
            {
                FileName = fileName ?? string.Empty;
                Path = path ?? string.Empty;
                Content = content ?? string.Empty;
            }

            public bool Equals(ScriptInfo other)
            {
                return string.Equals(Path, other.Path, StringComparison.OrdinalIgnoreCase)
                    && string.Equals(Content, other.Content, StringComparison.Ordinal);
            }

            public override bool Equals(object? obj)
            {
                return obj is ScriptInfo other && Equals(other);
            }

            public override int GetHashCode()
            {
                unchecked
                {
                    var h1 = StringComparer.OrdinalIgnoreCase.GetHashCode(Path);
                    var h2 = StringComparer.Ordinal.GetHashCode(Content);
                    return (h1 * 397) ^ h2;
                }
            }
        }

        private static Dictionary<string, string> BuildNodeTypeMap(Compilation compilation)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var attr = compilation.GetTypeByMetadataName("StateMachine.FSMNodeAttribute");
            if (attr == null) return result;

            void Traverse(INamespaceSymbol ns)
            {
                foreach (var m in ns.GetMembers())
                {
                    if (m is INamespaceSymbol childNs)
                    {
                        Traverse(childNs);
                    }
                    else if (m is INamedTypeSymbol type)
                    {
                        foreach (var a in type.GetAttributes())
                        {
                            if (!SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr)) continue;
                            string? key = null;
                            if (a.ConstructorArguments.Length > 0)
                            {
                                var arg = a.ConstructorArguments[0];
                                if (arg.Kind == TypedConstantKind.Primitive && arg.Value is string s) key = s;
                            }
                            if (key is null)
                            {
                                foreach (var na in a.NamedArguments)
                                {
                                    if (na.Key == "Key" && na.Value.Kind == TypedConstantKind.Primitive && na.Value.Value is string ks)
                                    {
                                        key = ks;
                                        break;
                                    }
                                }
                            }
                            if (!string.IsNullOrWhiteSpace(key))
                            {
                                var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                                if (!result.ContainsKey(key)) result[key] = fullName;
                            }
                        }
                    }
                }
            }
            Traverse(compilation.GlobalNamespace);
            return result;
        }

        private static List<NodeDef> ParseNodes(string script)
        {
            var list = new List<NodeDef>();
            var reader = new StringReader(script);
            string? line;
            while ((line = reader.ReadLine()) != null)
            {
                line = line.Trim();
                if (!line.StartsWith("def ", StringComparison.OrdinalIgnoreCase)) continue;
                var idxDef = line.IndexOf(' ');
                if (idxDef < 0) continue;
                var afterDef = line.Substring(idxDef + 1);
                var idxParenOpen = afterDef.IndexOf('(');
                var idxParenClose = afterDef.IndexOf(')');
                if (idxParenOpen < 0 || idxParenClose < 0 || idxParenClose <= idxParenOpen) continue;
                var name = afterDef.Substring(0, idxParenOpen).Trim();
                var typeKey = afterDef.Substring(idxParenOpen + 1, idxParenClose - idxParenOpen - 1).Trim();
                if (name.Length == 0 || typeKey.Length == 0) continue;
                list.Add(new NodeDef { NodeName = name, NodeTypeKey = typeKey });
            }
            return list;
        }
    }
}
