<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Naoki.AnotherFSM.FSMScriptAnalyzer</PackageId>
    <Version>1.1.1</Version>
    <Authors>Naoki</Authors>
    <Description>FSMScript 增量源生成器：将 .FSMScript 转换为强类型类。</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
  </ItemGroup>

  <!-- 将生成器程序集打包到 analyzers/dotnet/cs 路径 -->
  <ItemGroup>
    <None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StateMachine\StateMachine.csproj" />
  </ItemGroup>


</Project>
