<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- 引用源生成器 -->
  <ItemGroup>
    <ProjectReference Include="..\..\FSMNodeAnalyzer\FSMNodeAnalyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\FSMScriptAnalyzer\FSMScriptAnalyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <!-- 引用StateMachine项目 -->
  <ItemGroup>
    <ProjectReference Include="..\..\StateMachine\StateMachine.csproj" />
    <ProjectReference Include="..\..\demos\DemoNodes\DemoNodes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="*.FSMScript" />
  </ItemGroup>

</Project>
